abotmi/api/urls.py
from django.conf.urls import include, url
from . import uplyf_api_views
urlpatterns = [
    url(r'^get-auth-token/', 'rest_framework_jwt.views.obtain_jwt_token'),
    url(r'^api-token-verify/', 'rest_framework_jwt.views.verify_jwt_token'),
    url(r'^api-token-refresh','rest_framework_jwt.views.refresh_jwt_token'),
    url(r'^get-user-list/', 'api.views.get_user_list'),
    url(r'^get-user-details/', 'api.views.get_user_details'),
    url(r'^get-user-profile/', 'api.views.get_user_profile'),
    url(r'^test-list/', 'api.views.test_list'),
    url(r'^get-profile-details/', 'api.views.get_profile_details'),
    url(r'^send-mail-admin-subject/','api.views.send_mail_admin_subject'),
    url(r'^get-dashboard-details/','api.view.get_dashboard_details'),
    url(r'^get-raterank-details/','api.views.get_raterank_details'),
    url(r'^get-peerlist-torate','api.views.get_peerlist_torate'),
    url(r'^get-advisorloop-details','api.views.get_advisorloop_details'),
    url(r'^save-refer-advisor','api.views.save_refer_advisor'),
    url(r'^get-client-details','api.views.get_client_details'),
    url(r'^invite-peerto-rate','api.views.invite_peerto_rate'),
    url(r'^save-advisor-rank','api.views.rate_advisor'),
    url(r'^save-sale-accomplishment','api.views.save_sale_accomplishment'),
    url(r'^get-peerlist-torate','api.views.get_peerlist_torate'),
    url(r'^check-crisil-promocode','api.views.check_crisil_promocode'),
    url(r'^crisil-application','api.views.appling_crisil'),
    url(r'^upload-crisilref-document','api.views.crisil_submit_form'),
    url(r'^disown-member','api.views.disown_member'),
    url(r'^forgot-password','api.views.forgot_password_reset'),
    url(r'^get-in-touch','api.views.contact_us_reia'),
    url(r'^get-icore-specificposts','api.views.get_icore_specificposts'),
    url(r'^rate-icore-post','api.views.rate_icore_post'),
    url(r'^get-icore-categories','api.views.get_icore_categories'),
    url(r'^check-reg-user','api.views.is_register_user'),
     url(r'^aadhar_verification','api.views.aadhar_verification_data'),
    url(r'^is-registerd-user','api.views.is_registerd_user'),
    url(r'^check-email-exists','api.views.check_email_exists_send'),
    url(r'^advisor-events','api.views.get_advisor_events'),
    url(r'^create-direct-signup-user', 'api.views.create_direct_signup_user'),
    url(r'^submit-crisil-renewal','api.views.crisil_renew_submit'),
    url(r'^social-signup','api.views.social_signup_login_details'),
    url(r'^create-aadhaar-form-data','api.views.create_aadhaar_form_data'),
    url(r'^success','api.views.success'),
    url(r'^failure','api.views.failure'),
    url(r'^member-success','api.views.member_sucess'),
    url(r'^member-failed','api.views.member_failed'),
    url(r'^sms-status','api.views.get_smsalert_status'),
    url(r'^change-sms-status','api.views.change_sms_status'),
    url(r'^change-password','api.views.user_createpassword'),
    url(r'^webinar','api.views.create_webinar_mobile'),
    url(r'^uplyfdetails','api.views.uplyfdetails_mobile'),
    url(r'^meetupupdate','api.views.meetupupdate'),  
    url(r'^meetup','api.views.create_meetup_mobile'),
    url(r'^mygrowth_mobile','api.views.create_mygrowth_mobile'),
    url(r'^my_webinar_room_name','api.views.my_webinar_room_name'),
    url(r'^mee_mobile','api.views.list_meetup_mobile'),
    url(r'^web_mobile','api.views.list_webinar_mobile'),
    url(r'^list_member_invitation', 'api.views.list_member_invitation_mobile'),
    url(r'^register_member_webinar', 'api.views.register_member_webinar_mobile'),
    url(r'^delete_meetup','api.views.delete_meetup_event_mobile'),
    url(r'^delete_webinar','api.views.delete_webinar_event_mobile'),
    url(r'^list_mail','api.views.list_mail_invitation_mobile'),
    url(r'^icore-add-media','api.views.icore_add_media'),
    url(r'^icore-add-post','api.views.icore_add_post'),
    url(r'^icore-add-comment','api.views.icore_add_comment'),
    url(r'^upload-file','api.views.upload_file'),
    url(r'^update-profile-details','api.views.save_profile'),
    url(r'^download-profile','api.views.download_advisor_profile'),
    url(r'^add-client-email','api.views.save_new_member'),
    url(r'^check_aadhaar_present','api.views.check_aadhaar_present'),
    url(r'^member_success','api.views.member_success'),
    url(r'^member_failure','api.views.member_failure'),
    url(r'^manage_client_transactions','api.views.manage_client_transactions'),
    url(r'^register_user','api.views.register_user'),
    url(r'^user-profile-answer','api.views.user_profile_answer'),
    url(r'^get-digital-link','api.views.get_digital_link'),
    url(r'^save-digital-link','api.views.save_digital_link'),
    url(r'^delete-digital-link','api.views.delete_foot_print'),
    url(r'^advisor-profile-answer','api.views.advisor_profile_answer'),
    url(r'^user-profile-basicdetails-details','api.views.user_profile_basicdetails_details'),
    url(r'^country-details','api.views.country_details'),
    url(r'^m-submit-eipv','api.views.m_submit_eipv'),
    url(r'^m-upload-eipv-documents','api.views.m_upload_eipv_documents'),
    url(r'^m_delete_uploaded_documents','api.views.delete_uploaded_documents'),
    url(r'^m-eipv-form','api.views.m_eipv_form'),
    url(r'^m-send-otp','api.views.m_send_otp'),
    url(r'^m-verify-otp','api.views.m_verify_otp'),
    url(r'^get-myidentity','api.views.get_myidentity_details'),
    url(r'^get-myhub-details','api.views.get_myhub_details'),
    url(r'^check_refer_advisor_email','api.views.check_refer_advisor_email'),
    url(r'^list_enquiried_clients','api.views.list_enquiried_clients'),
    url(r'^list_client_enquiry','api.views.list_client_enquiry'),
    url(r'^m-geteipv-data','api.views.m_geteipv_data'),
    url(r'^advisor_video_upload_api','api.views.advisor_video_upload_api'),
    url(r'^advisor_video_publish_api','api.views.advisor_video_publish_api'),
	url(r'^send_meetup_invitation_mail','api.views.send_meetup_invitation_mail'),
    url(r'^save_language','api.views.save_language_details'),
    url(r'^save_mypromise','api.views.save_mypromise'),
    url(r'^save_mybelief','api.views.save_mybelief'),
    url(r'^save_contectdetails','api.views.save_contectdetails'),
    url(r'^save_skills','api.views.save_skillsdetails'),
    url(r'^save_advisory_specialization','api.views.save_advisory_specialization'),
    url(r'^save_additional_qualification','api.views.save_additional_qualification'),
    url(r'^regulatory_certification_registration','api.views.regulatory_certification_registration'),
    url(r'^save_clients','api.views.save_clients'),
    url(r'^save_advisor','api.views.save_advisor'),
    url(r'^save_aboutme','api.views.save_aboutme'),
    url(r'^check_adhaar','api.views.is_adharregister_user'),
    url(r'^save_adhaar','api.views.save_adhaar'),
    url(r'^education_detail','api.views.education_details'),
    url(r'^direct_signup','api.views.direct_signup'),
    url(r'^check-email/','api.views.checkEmail'),
    url(r'^save_country_details','api.views.save_country'), 
    url(r'^signup-send-otp','api.views.signup_send_otp'),
    url(r'^signup-resend-otp','api.views.resend_email_mobile_otps_mob'),
    url(r'^validate-otp','api.views.validate_otp_mob'),
    url(r'^save_education_details','api.views.save_educationDetails'),
    url(r'^logout-user','api.views.logout_user'),
    url(r'^save_certification_details','api.views.save_certificationDetails'),
    url(r'^get_server_ip', 'api.views.get_server_ip', name='get_server_ip'),
    # geo reverse coding
    url(r'^get-geo-location/', 'api.views.get_geo_location', name='get_geo_location'),
    # UPLYF API VIEWS
    url(r'^advisor-selection/', uplyf_api_views.advisor_selection),
    url(r'^get_companies_list/', uplyf_api_views.get_companies_list, name="get_companies_list"),
    url(r'^upwrdz_add_client_email/',uplyf_api_views.save_new_member_upwrdz, name="save_new_member_upwrdz"),
    url(r'^get-companies-advisors-list/', uplyf_api_views.get_companies_advisors_list, name='get_companies_advisors_list'),
    url(r'^get-all-register-advisors/', uplyf_api_views.get_all_register_advisors),
    url(r'^get_webniar_list/', uplyf_api_views.get_webniar_list, name="get_webniar_list"),
    url(r'^get_meetup_list/', uplyf_api_views.get_meetup_list, name="get_meetup_list"),
    url(r'^get-advisor-profile-link/', uplyf_api_views.get_advisor_profile_link, name='get_advisor_profile_link'),
    url(r'^get_profile_card', 'api.views.get_profile_card'),
    url(r'^save-client-notification-upwrdz/',
        uplyf_api_views.save_client_notification_upwrdz, 
        name='save-client-notification-upwrdz'
    ),
    url(r'^increament_registered_user_count_by_event_id/',
        uplyf_api_views.increament_registered_user_count_by_event_id,
        name='increament_registered_user_count_by_event_id'
    ),
    
    # FASIA API URLS
    url(r'^check_and_register/', 'api.views.check_and_register', name='check_and_register'),
    url(r'^check_auth_and_redirect/',
        'api.views.check_auth_and_redirect', name='check_auth_and_redirect'),
    url(r'^save_calendly_link','api.views.calendly_save_link')    
     
]

abotmi/reia/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from login import views as login_views
from . import views
from home import views as home_views

from my_identity.views import index, guest_details
from my_repute.views import demo_repute
from signup.views import investor_identity

admin.autodiscover()

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^home/', home_views.index, name='index'),
    url(r'^login/', include('login.urls'), name='login'),
    url(r'^logout/', login_views.user_logout, name='logout'),
    url(r'^nfadmin/', include('nfadmin.urls', namespace='nfadmin')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/', views.get_protected_media, name='get_protected_media'),
    # URL based redirection need to implement
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^signup/', include('signup.urls', namespace='signup')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^webinar/', include('webinar.urls', namespace='webinar')),
    url(r'^meetup/', include('meetup.urls', namespace='meetup')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^guest/(?P<slug>[A-Za-z0-9_-]+)/$', guest_details, name='guest'),
    url(r'^profile/(?P<slug>[A-Za-z0-9_-]+)/$', index, name='profile'),
    url(r'^investor_profile/(?P<slug>[A-Za-z0-9_-]+)/$',
        investor_identity, name='investor_identity'),
    url(r'^repute_index/(?P<slug>[A-Za-z0-9_-]+)/$', demo_repute, name='demo_repute'),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^advisor_check/', include('advisor_check.urls', namespace='advisor_check')),
    url(r'^aadhaar/', include('aadhaar.urls', namespace='aadhaar')),
    url(
        r'^reputation-index/', include(
            'reputation_index.urls', namespace='reputation-index')
    ),
    url(r'^my_identity/', include('my_identity.urls', namespace='my_identity')),
    url(r'^revenue/', include('revenue.urls', namespace='revenue')),
    url(r'^my_growth/', include('my_growth.urls', namespace='my_growth')),
    url(r'^my_repute/', include('my_repute.urls', namespace='my_repute')),
    url(r'^revenue/', include('revenue.urls', namespace='revenue')),
    url(r'^subscribe/', include('subscribe.urls', namespace='subscribe')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^bcadmin/', include('bcadmin.urls', namespace='bcadmin')),
    url(r'^wpb/', include('wpb.urls', namespace='wpb')),

]

abotmi/webinar/urls.py
from django.conf.urls import url

from . import views
from .views import WebinarMemberRegistration

urlpatterns = [
    url(r'^$',views.dashboard, name='dashboard'),
    url(r'^create_webinar/$',views.create_webinar, name='create_webinar'),
    url(r'^delete_webinar/$',views.delete_webinar, name='delete_webinar'),
    url(r'^check_room_name/$',views.check_room_name, name='check_room_name'),
    url(
        r'^register_member/(?P<room_id>[a-zA-Z0-9]\w{6})/$',
        WebinarMemberRegistration.as_view(),
        name='register_member'
    ),
]

abotmi/datacenter/models/webinar.py
'''
author: Kantanand US
created date: 12-05-2016
'''

import datetime
from django.db import models
from simple_history.models import HistoricalRecords

from datacenter.models import UserProfile

class TrackWebinar(models.Model):
	room_id = models.CharField(max_length=10, null=True, blank=True, default="0")
	room_name = models.CharField(max_length=250, null=True, blank=True, default="None")
	room_url = models.CharField(max_length=250, null=True, blank=True)
	room_pin = models.CharField(max_length=10, null=True, blank=True)
	room_type = models.CharField(max_length=10,blank=True,default='webinar')
	starts_at = models.DateTimeField(blank=True, null=True)
	duration = models.DurationField(default=datetime.timedelta(0))
	session_id = models.CharField(max_length=10, blank=True, null=True)
	session_data = models.TextField(blank=True)
	session_ended = models.BooleanField(default=0)
	password = models.CharField(max_length=50, null=True, blank=True)
	user_profile = models.ForeignKey(UserProfile, blank=True, null=True)
	auto_login_host_url = models.TextField(null=True, blank=True)
	# uplyf project 
	uplyf_project = models.TextField(null=True, blank=True)
	created_date = models.DateTimeField(auto_now_add = True, blank=True, null=True)
	modified_date = models.DateTimeField(auto_now = True, blank=True, null=True)
	# Historical data ===========
	history = HistoricalRecords()

	class Meta:
			app_label = 'datacenter'
			managed = True

	def __unicode__(self):
		return 'Room id: '+self.room_id +' Name: '+ self.room_name

abotmi/webinar/models.py
from django.db import models

# Create your models here.

abotmi/webinar/forms.py
# python lib
import datetime
from datetimewidget.widgets import DateTimeWidget
# Django lib
from django import forms
# Constans
from . import constants
# Local imports
from common.views import get_uplyf_project_list


def get_my_choices():
    '''
    Getting Projects list from UPLYF
    '''
    project_result = get_uplyf_project_list()
    total_projects_list = [
        ('', 'Select')
    ]
    if project_result:
        project_result_list = [((p['project_name']+'-'+p['project_id']),(p['project_name']+'-'+p['project_id']))for p in project_result]
        total_projects_list = total_projects_list + project_result_list
    return total_projects_list


class CreateWebinarForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(CreateWebinarForm, self).__init__(*args, **kwargs)
        # self.fields['uplyf_project'] = forms.ChoiceField(
        #     required=False, choices=get_my_choices() )

    today = str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    dateTimeOptions = {
        'format': 'yyyy-mm-dd hh:ii:ss',
        'autoclose': True,
        'showMeridian' : True,
        'startDate': '%s' %today
    }

    name = forms.CharField(
                max_length = 50,
                label = 'Room Name *',
                required = True,
                widget=forms.TextInput(
                    attrs={
                        'placeholder': 'Room Name'
                    }
                )
            )
    lobby_description = forms.CharField(
                            label = 'Lobby Description *',
                            widget = forms.Textarea(attrs={
                                'placeholder': 'Lobby Description'
                            }),
                            required = True,
                        )
    starts_at = forms.DateTimeField(
                    label = 'Schedule Date & Time *',
                    widget = DateTimeWidget(
                        attrs={
                            'required':'true',
                            'onfocus':'enable_starts_at();',
                            'onblur':'disable_starts_at();',
                            'placeholder':'Schedule Date & Time'
                        },
                        options = dateTimeOptions,
                        bootstrap_version = 3
                    ),
                    required = True
                )
    duration = forms.IntegerField(
                    label = 'Duration in Minutes *',
                    required = True,
                    widget=forms.TextInput(attrs={
                        'placeholder': 'Duration in Minutes'
                    })
                )

abotmi/templates/webinar/list_members_and_advisors.html
{% extends 'webinar/webinar_home.html' %}
{% load staticfiles %}
{% block custom_theme_css %}
{{block.super}}
<style>
    .webinar-reg-btn{
        font-size: 12px;
    }
</style>
{% endblock %}
{% block main_content %}
    <section class="subpage-reia-primary" id="about">
        <div class="container">
            <div class="row n-margin-0">
                <div class="col-md-8">
                    {% include 'webinar/common_list_members.html' with view_members=final_total_members user_profile_obj=final_total_advisors %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block scripts %}
<script src="/static/admin_theme/plugins/datatables/jquery.dataTables.js"
        type="text/javascript"></script>
<script src="/static/admin_theme/plugins/datatables/dataTables.bootstrap.js"
        type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#table_id').dataTable({
                "orderFixed": [ 0, 'asc' ]
            });
            row_ids = $("#table_id_wrapper").find('.row');
            for (i=0; i < row_ids.length; i++){
                $("."+row_ids[i].className).addClass('n-margin-lr-0');
            }
    });
    </script>
    <script type="text/javascript">
        var token = '{{csrf_token}}';
        function register_member(id, type) {
            $.ajax({
                type: 'POST',
                beforeSend: function(request) {
                    request.setRequestHeader("X-CSRFToken",token);
                },
                url: '{% url "webinar:register_member" room_id=room_id %}',
                data: {
                    'member_details' : $("#"+type+id.toString()).val(),
                },
                success: function (response) {
                    if(response == 'success'){
                        var parent_td = $('#'+id).parent();
                        $("#"+id).remove();
                        parent_td.html('<span class="label label-success">Registered</span>');
                    }
                },
                error: function (response) {
                    alert('unable to register');
                }
            });
        }
    </script>
{% endblock %}
{% block theme_scripts %}
    {{block.super}}
{% endblock %}

abotmi/templates/webinar/webinar_meetings_list.html
{% extends 'webinar/webinar_home.html' %}
{% load staticfiles %}
{% block important_css %}
{% endblock %}
{% block top_header %}
    {% include 'header2.html' %}
{% endblock %}
{% block custom_theme_css %}
<link href="/static/admin_theme/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="{% static 'css/new_css/header2.css' %}">
<link rel="stylesheet" href="{% static 'css/new_css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/new-datatable.css' %}">
<style type="text/css">
    .mrg-80{
        margin-top: 80px;
        margin-bottom: 80px;
    }
    .input-sm{
        color: #fff;
    }
    .webinar-table-div #table_id th{
        max-width: 100px !important;
    }
    .webinar-table-div #table_id th{
        max-width: 100px !important;
    }
    .webinar-table-div .table tbody > tr > td{
        max-width: 100px;
        word-wrap: break-word !important;
    }
    .webinar-table-div .table tbody > tr > td:last-child a{
        margin: 5px;
        font-size: 14px;
    }
    .delete-webinar-div{
        border-top: 0px;
    }
</style>
{% endblock %}

{% block main_content %}
<section class="subpage-reia-primary mrg-80 parent-section" id="about">
    <div class="container">
    {% if user.profile.advisor.is_register_advisor %}
        <div clas="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <a href="{% url 'webinar:create_webinar' %}" class="btn upwrdz-button">CREATE WEBINAR</a>
                <!-- Note : this code will bring clickmeeting dashboard -->
                <!-- <a href="{% url 'webinar:dashboard' %}" class="btn btn-success">Webinar Dashboard</a> -->
            </div>
        </div>
        <br><br><br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="box-body webinar-table-div">
                <div class="table-responsive">
                    <table id="table_id" name="table_id" class="table table-bordered">
                        <span class="pull-right">
                            <a id="veiw-member-search-icon" onclick="enable_search()"><i class="fa fa-search-thin fa-lg"></i></a>
                        </span>
                        <thead>
                            <tr>
                                <th>SL.NO</th>
                                <th>ROOM NAME</th>
                                <th>PROJECT NAME</th>
                                <th>START TIME</th>
                                <th>MANAGE ROOM</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for objects in list_of_webinars %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ objects.room_name }}</td>
                                <td>{{ objects.uplyf_project }}</td>
                                <td>{{ objects.starts_at}}</td>
                                <td>
                                    <a href="{{objects.room_url}}?l={{objects.auto_login_host_url}}" target="_blank" class="btn upwrdz-button" title="Go">Go</a>
                                    <a onclick="is_confirm_delete('{{ objects.room_id }}');" class="btn upwrdz-button" title="Delete">X</a>
                                    {% if not user_profile == objects.user_profile %}
                                        <a href="{% url 'webinar:register_member' room_id=objects.room_id %}" class="btn upwrdz-button" title="REGISTER">Register</a>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div><!-- /.box-body -->
        </div>
    </div><!-- /.row -->
    {% else %}
    <div clas="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h3> You must be as registered advisor in ABOTMI </h3>
            </div>
    </div>
    {% endif %}
    </div>
</section>
{% endblock %}
{% block bootstrap-modal %}
    <div class="modal fade" id="refer-member-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
      <div class="modal-dialog">
            <div class="panel panel-default popup-panel">
                <div class="panel-heading dash-heading">
                    <h4><label><img src="/static/images/dash-img01.png" /></label>
                    <span>Refer a Member</span><span class="pull-right"><i class="fa fa-times-circle" data-dismiss="modal" aria-hidden="true"></i></span></h4>
                </div>
                <div class="panel-body pannel-popup-content" id="refer-member-modal-body">
                    <div class="text-center">
                        <span><input type="submit" class="btn btn-primary popup-btn" value="Additional info"></span>
                        <span><input type="submit" class="btn btn-primary popup-btn" value="Submit"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade upwardz-modal" id="id_confirm_modal" name="id_confirm_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="panel upwrdz-log-panel panel-default">
                    <div class="modal-header modal-header-border-bottom text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <i class="fa fa-times-thin fa-2x"></i>
                        </button>
                        <h3><span class="modal-title n-span-blue-color">CONFIRM</span></h3>
                        <hr class="modal-heading-hr">
                    </div>
                    <div class="panel-body pannel-popup-content text-center" id="id_confirm_modal_body">
                    </div>
                    <div class="modal-footer delete-webinar-div text-center" id="id_confirm_modal_footer">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="hidden" id="confirm_delete_webinar_button">
        <button type="button" name="cancel_delete" id="id_cancel_delete" class="btn upwrdz-button" data-dismiss="modal">Cancel</button>
        <button type="button" name="delete_webinar" id="id_delete_webinar" class="btn upwrdz-button">Ok</button>
    </div>
    <!-- ###############  Thank you Modal pop up #################### -->
    <div class="modal fade upwardz-modal" id="webinar_invitation_message" name="webinar_invitation_message" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-md upwrdz-view-client-model upwrdz-view-peerclient-model">
            <div class="modal-content">
                <div class="panel upwrdz-log-panel panel-default">
                    <div class="modal-header modal-header-border-bottom text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-times-thin fa-2x"></i>
                        </button>
                        <h3 class="modal-title n-span-blue-color"> Thank You</h3>
                        <hr class="modal-heading-hr">
                    </div>
                    <div class="panel-body pannel-popup-content">
                        <p class="text-center">Webinar created successfully.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
<!-- Scripts Start Here -->
<!-- DATA TABES SCRIPT -->
<script src="/static/admin_theme/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="/static/admin_theme/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#table_id').dataTable({
            language: {
                paginate: {
                    previous: "< Previous",
                    next: "Next >"
                }
            }
        });
        document.getElementById('table_id_filter').style.display = 'none';
    });
    function enable_search(){
        document.getElementById('table_id_filter').style.display = 'block';
        document.getElementById('veiw-member-search-icon').style.display = 'none';
    }
    function delete_webinar(room_id){
        var token = "{{ csrf_token }}";
        $.ajax({
            url: "{% url 'webinar:delete_webinar' %}",
            type: 'POST',
            beforeSend: function(request) {
                request.setRequestHeader("X-CSRFToken",token);
            },
            data: { room_id: room_id },
            success: function(response){
                if(response == 'success'){
                    window.location.reload();
                } else {
                    alert('your not authorized to delete this evevnt or event does not exists');
                }
            }
        });
    }
    // Confirmation for deleting the webinar
    function is_confirm_delete(id){
        $("#id_confirm_modal_body").html('Do you want to delete this webinar ?');
        $("#id_delete_webinar").attr('onclick', 'delete_webinar("'+id+'")');
        $("#id_confirm_modal_footer").html(
            $("#confirm_delete_webinar_button").html()
        )
        $("#id_confirm_modal").modal('show');
    }
</script>
{% endblock %}
{% block theme_scripts %}
   {{block.super}}
   {% if is_webinar_created %}
   <script type="text/javascript">
        $("#webinar_invitation_message").modal('show');
   </script>
   {% endif %}
{% endblock %}